// <auto-generated />
using System;
using EComm_2112510116.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EComm_2112510116.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EComm_2112510116.Shared.Kategori", b =>
                {
                    b.Property<int>("IdKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategori"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategori");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            IdKategori = 1,
                            Nama = "Crime"
                        },
                        new
                        {
                            IdKategori = 2,
                            Nama = "Thriller"
                        },
                        new
                        {
                            IdKategori = 3,
                            Nama = "Drama"
                        });
                });

            modelBuilder.Entity("EComm_2112510116.Shared.Produk", b =>
                {
                    b.Property<int>("IdProduk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduk"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GambarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("HargaOriginal")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("IdKategori")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VarianIdVarian")
                        .HasColumnType("int");

                    b.HasKey("IdProduk");

                    b.HasIndex("IdKategori");

                    b.HasIndex("VarianIdVarian");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            IdProduk = 1,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Misteri Tujuh Lonceng adalah sebuah novel yang bercerita tentang pembunuhan seorang Pegawai Departemen Luar Negeri Inggris di sebuah pemondokan, yaitu pemondokan Chimney. Setelah itu Terjadi juga pembunuhan terhadap seorang pria yang tidak lain adalah teman orang yang terbunuh di pemondokan Chimney.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/4/4c/The_Seven_Dials_Mystery_First_Edition_Cover_1929.jpg",
                            Harga = 99.999m,
                            HargaOriginal = 100.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Misteri Tujuh Lonceng"
                        },
                        new
                        {
                            IdProduk = 2,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Dalam buku ini, Hercule Poirot menerima telegram dari miliarder bernama Paul Renauld, yang memintanya datangke vilanya di Prancis. Saat Poirot tiba, Renauld telah meninggal; tubuhnya ditusuk dan terbaring disebuah lapangan golf.Istrinya mengklaim bahwa ia telah diculik oleh dua orang Chili. Ternyata kemudian diketahui bahwa Renauld telah merencanakanuntuk memalsukan kematiannya sendiri, tetapi (tentu saja) kemudian terjadi peristiwa-peristiwa yang merusak rencananya.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/f/f0/Lapangangolfmaut.jpg",
                            Harga = 89.999m,
                            HargaOriginal = 100.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Lapangan Golf Maut"
                        },
                        new
                        {
                            IdProduk = 3,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Empat Besar atau The Big Four adalah novel detektif fiksi karya Agatha Christie dan pertama kali diterbitkan di Britania Raya oleh William Collins & Sons pada tanggal 27 Januari 1927 dan di Amerika Serikat oleh Dodd, Mead and Company pada tahun yang sama.Novel ini menampilkan karakter Hercule Poirot, Arthur Hastings dan Chief Inspector Japp.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/4/49/The_Big_Four_First_Edition_Cover_1927.jpg",
                            Harga = 59.999m,
                            HargaOriginal = 100.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Empat Besar"
                        },
                        new
                        {
                            IdProduk = 4,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Penelusuran Benang Merah (judul asli dalam bahasa Inggris: A Study in Scarlet)adalah novel fiksi detektif karya Sir Arthur Conan Doyle yang memperkenalkan tokoh detektif konsultan rekaannya, Sherlock Holmes,serta sahabat sekaligus penulis kisah petualangannya, dr. Watson, yang kelak akanmenjadi dua tokoh terkenal dalam dunia sastra.\r\n",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/5/56/Penelusuran_Benang_Merah.jpg",
                            Harga = 129.999m,
                            HargaOriginal = 300.000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Penelusuran Benang Merah"
                        },
                        new
                        {
                            IdProduk = 5,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Empat Pemburu Harta (judul asli dalam bahasa Inggris:The Sign of Four) adalah novel kedua karya Sir Arthur Conan Doyle yang menampilkan Sherlock Holmes, terbit pertama kali pada tahun 1890 di Lippincott's Monthly Magazine.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/9/96/Empat_Pemburu_Harta.jpg",
                            Harga = 149.999m,
                            HargaOriginal = 500.000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Empat Pemburu Harta"
                        },
                        new
                        {
                            IdProduk = 6,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Lembah Ketakutan atau The Valley of Fear adalah novel Sherlock Holmes keempat dan terakhir karya Sir Arthur Conan Doyle. Karya tersebut berdasarkan pada Molly Maguires dan agen Pinkerton James McParland. Cerita tersebut mula-mula trbit dalam Strand Magazine antara September 1914 dan Mei 1915. Edisi buku pertamanya diberi hak cipta pada 1914, dan karya tersebut mulamula diterbitkan oleh George H. Doran Company di New York pada 27 Februari 1915, dan diilustrasikan oleh Arthur I. Keller..",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/commons/8/84/Valley_of_fear.jpg",
                            Harga = 139.999m,
                            HargaOriginal = 300.000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Lembah Ketakutan"
                        },
                        new
                        {
                            IdProduk = 7,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Laskar Pelangi adalah novel pertama karya Andrea Hirata yang diterbitkan oleh Bentang Pustaka pada tahun 2005. Novel ini bercerita tentang kehidupan 10 anak dari keluarga miskin yang bersekolah (SD dan SMP) disebuah sekolah Muhammadiyah di Belitung yang penuh dengan keterbatasan..",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/8/8e/Laskar_pelangi_sampul.jpg",
                            Harga = 99.999m,
                            HargaOriginal = 150.000m,
                            IdKategori = 3,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Laskar Pelangi"
                        },
                        new
                        {
                            IdProduk = 8,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Sang Pemimpi Baru adalah novel kedua dalam tetralogi Laskar Pelangi karya Andrea Hirata yang diterbitkan oleh Bentang Pustaka pada Juli 2006. Dalam novel ini, Andrea mengeksplorasi hubungan persahabatannya dengan dua anak yatim piatu, Arai Ichsanul Mahidin dan Jimbron, serta kekuatan mimpi yang dapat membawa Andrea dan Arai melanjutkan studi ke Sorbonne, Paris, Prancis.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/8/89/Sang_Pemimpi_sampul.jpg",
                            Harga = 99.999m,
                            HargaOriginal = 150.000m,
                            IdKategori = 3,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Sang Pemimpin"
                        },
                        new
                        {
                            IdProduk = 9,
                            DateCreated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deskripsi = "Edensor adalah buku ketiga dari Tetralogi Laskar Pelangi karya Andrea Hirata yang diterbitkan oleh Bentang Pustaka pada bulan Mei tahun 2007. Buku berikutnya dan yang terakhir adalah Maryamah Karpov. Edensor masuk nominasi penghargaan nasional sastra KLA (Khatulistiwa Literary Award) tahun 2007.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/e/ec/Edensor_sampul.jpg",
                            Harga = 99.999m,
                            HargaOriginal = 150.000m,
                            IdKategori = 3,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Edensor"
                        });
                });

            modelBuilder.Entity("EComm_2112510116.Shared.Varian", b =>
                {
                    b.Property<int>("IdVarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVarian"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVarian");

                    b.ToTable("Varian");

                    b.HasData(
                        new
                        {
                            IdVarian = 1,
                            Nama = "Soft Cover"
                        },
                        new
                        {
                            IdVarian = 2,
                            Nama = "Hard Cover"
                        },
                        new
                        {
                            IdVarian = 3,
                            Nama = "Digital"
                        });
                });

            modelBuilder.Entity("EComm_2112510116.Shared.Produk", b =>
                {
                    b.HasOne("EComm_2112510116.Shared.Kategori", "Kategori")
                        .WithMany("Produk")
                        .HasForeignKey("IdKategori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EComm_2112510116.Shared.Varian", null)
                        .WithMany("Produk")
                        .HasForeignKey("VarianIdVarian");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EComm_2112510116.Shared.Kategori", b =>
                {
                    b.Navigation("Produk");
                });

            modelBuilder.Entity("EComm_2112510116.Shared.Varian", b =>
                {
                    b.Navigation("Produk");
                });
#pragma warning restore 612, 618
        }
    }
}
